## 1. Import Libraries

We install and import the necessary Python libraries required for data manipulation (`pandas`, `numpy`) and set standard Pandas display options so that large tables aren't truncated.

In [15]:
# Install all required dependencies for reading and styling
%pip install pandas numpy openpyxl jinja2 matplotlib

import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)

Requirement already satisfied: pandas in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (2.4.4)
Requirement already satisfied: openpyxl in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: jinja2 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.1.6)
Requirement already satisfied: matplotlib in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.11.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\polai\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from jinja2) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\polai\appdata\roaming\python\python313\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=9 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\polai\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## 2. Project Path

We dynamically locate the project root directory and define the path to our raw dataset (`companies.xlsx`). This code automatically detects if you are running it from inside the `notebooks` folder or the project root!

In [16]:
current_dir = Path.cwd()

# Dynamically determine project root
if current_dir.name == "notebooks":
    PROJECT_ROOT = current_dir.parent
else:
    PROJECT_ROOT = current_dir

DATA_PATH = PROJECT_ROOT / "data" / "raw"
COMPANY_FILE = DATA_PATH / "companies.xlsx"

print("Project Root:", PROJECT_ROOT)
print("Company File:", COMPANY_FILE)

Project Root: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform
Company File: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform\data\raw\companies.xlsx

## 3. Read Dataset

We load the Excel dataset into a Pandas DataFrame so we can begin our exploration and manipulation.

In [17]:
try:
    df = pd.read_excel(COMPANY_FILE)
    print("Dataset Loaded Successfully")
    display(df.head())
except Exception as e:
    print(f"Error loading dataset: {e}")

Dataset Loaded Successfully

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

## 4. Dataset Overview

We print the fundamental shape of our dataset to understand its scale (total number of rows and columns).

In [18]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

============================================================
DATASET OVERVIEW
============================================================
Rows    : 93
Columns : 12

## 5. Column Names

We extract and list all the column names present in the dataset. This acts as our initial data dictionary.

In [19]:
columns = pd.DataFrame({
    "Column Name": df.columns
})
columns

                                          Column Name
0   Mkt Fintech — Nifty 100  |  Companies  |  92 r...
1                                          Unnamed: 1
2                                          Unnamed: 2
3                                          Unnamed: 3
4                                          Unnamed: 4
5                                          Unnamed: 5
6                                          Unnamed: 6
7                                          Unnamed: 7
8                                          Unnamed: 8
9                                          Unnamed: 9
10                                        Unnamed: 10
11                                        Unnamed: 11

## 6. Data Types

We inspect the data types of each column (e.g., `int64`, `float64`, `object`/string) to ensure Pandas interpreted them correctly.

In [20]:
dtype_df = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str)
})
dtype_df

                                                                                               Column Data Type
Mkt Fintech — Nifty 100  |  Companies  |  92 re...  Mkt Fintech — Nifty 100  |  Companies  |  92 r...       str
Unnamed: 1                                                                                 Unnamed: 1       str
Unnamed: 2                                                                                 Unnamed: 2       str
Unnamed: 3                                                                                 Unnamed: 3       str
Unnamed: 4                                                                                 Unnamed: 4       str
Unnamed: 5                                                                                 Unnamed: 5       str
Unnamed: 6                                                                                 Unnamed: 6       str
Unnamed: 7                                                                                 Unnamed: 7       str
Unnamed: 8                                                                                 Unnamed: 8    object
Unnamed: 9                                                                                 Unnamed: 9    object
Unnamed: 10                                                                               Unnamed: 10    object
Unnamed: 11                                                                               Unnamed: 11    object

## 7. Missing Values

We calculate the absolute count and percentage of missing (null/NaN) values for each column. High missing percentages might require imputation or dropping the column entirely.

In [21]:
missing = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})

missing.sort_values("Missing Values", ascending=False)

                                                                                               Column  Missing Values  Percentage
Unnamed: 11                                                                               Unnamed: 11               2        2.15
Unnamed: 1                                                                                 Unnamed: 1               1        1.08
Unnamed: 5                                                                                 Unnamed: 5               1        1.08
Unnamed: 7                                                                                 Unnamed: 7               1        1.08
Unnamed: 9                                                                                 Unnamed: 9               1        1.08
Unnamed: 8                                                                                 Unnamed: 8               1        1.08
Unnamed: 10                                                                               Unnamed: 10               1        1.08
Unnamed: 6                                                                                 Unnamed: 6               1        1.08
Unnamed: 3                                                                                 Unnamed: 3               0        0.00
Unnamed: 2                                                                                 Unnamed: 2               0        0.00
Mkt Fintech — Nifty 100  |  Companies  |  92 re...  Mkt Fintech — Nifty 100  |  Companies  |  92 r...               0        0.00
Unnamed: 4                                                                                 Unnamed: 4               0        0.00

## 8. Duplicate Records

We check for completely identical rows across all columns, which could skew our analysis if left untreated.

In [22]:
duplicates = df.duplicated().sum()
print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

## 9. Unique Values

We count the number of distinct, unique values in each column. This helps identify categorical variables or unique identifiers (like a Company ID).

In [23]:
unique = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": df.nunique()
})
unique

                                                   count unique                                                top freq
Mkt Fintech — Nifty 100  |  Companies  |  92 re...    93     93                                                 id    1
Unnamed: 1                                            92     91  https://mkt.in/static/mkt-icons/nifty100/HEROM...    2
Unnamed: 2                                            93     93                                       company_name    1
Unnamed: 3                                            93     55  https://in.tradingview.com/chart/qGsydD2w/?sym...   39
Unnamed: 4                                            93     93                                      about_company    1
Unnamed: 5                                            92     91                       https://www.bajajfinserv.in/    2
Unnamed: 6                                            92     92                                        nse_profile    1
Unnamed: 7                                            92     92                                        bse_profile    1
Unnamed: 8                                            92      5                                                 10   31
Unnamed: 9                                            92     85                                                275    3
Unnamed: 10                                         92.0   85.0                                               13.2  3.0
Unnamed: 11                                         91.0   86.0                                               57.1  2.0

## 10. Descriptive Statistics

We generate summary statistics (mean, median, standard deviation, min, max, and quartiles) to understand the distribution of our numerical columns.

In [24]:
df.describe(include="all").T

                                                                                               Column  Unique Values
Mkt Fintech — Nifty 100  |  Companies  |  92 re...  Mkt Fintech — Nifty 100  |  Companies  |  92 r...             93
Unnamed: 1                                                                                 Unnamed: 1             91
Unnamed: 2                                                                                 Unnamed: 2             93
Unnamed: 3                                                                                 Unnamed: 3             55
Unnamed: 4                                                                                 Unnamed: 4             93
Unnamed: 5                                                                                 Unnamed: 5             91
Unnamed: 6                                                                                 Unnamed: 6             92
Unnamed: 7                                                                                 Unnamed: 7             92
Unnamed: 8                                                                                 Unnamed: 8              5
Unnamed: 9                                                                                 Unnamed: 9             85
Unnamed: 10                                                                               Unnamed: 10             85
Unnamed: 11                                                                               Unnamed: 11             86

## 11. Sample Records

We randomly sample a few records to visually inspect the actual contents and context of the data.

In [25]:
df.sample(10, random_state=42)

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
40,HDFCLIFE,https://mkt.in/static/mkt-icons/nifty100/HDFCL...,HDFC Life Insurance Company Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,HDFC Life Insurance Company is engaged in carr...,http://www.hdfclife.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/hdf...,10,73,6.61,11.4
22,BRITANNIA,https://mkt.in/static/mkt-icons/nifty100/BRITA...,Britannia Industries Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,Britannia Industries is one of Indias leading ...,https://www.britannia.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/bri...,1,133,48.9,57.1
55,JIOFIN,https://mkt.in/static/mkt-icons/nifty100/JIOFI...,Jio Financial Services Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Jio Financial Services Ltd is an Indian financ...,https://www.jfs.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://bseindia.com/stock-share-price/jio-fin...,10,216,2.16,1.82
72,PIDILITIND,https://mkt.in/static/mkt-icons/nifty100/PIDIL...,Pidilite Industries Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Pidilite Industries Limited is a leading manuf...,http://www.pidilite.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/pid...,1,171,29.7,22.8
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
26,COALINDIA,https://mkt.in/static/mkt-icons/nifty100/COALI...,Coal India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Coal India Ltd is mainly engaged in mining and...,http://www.coalindia.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/coa...,10,156,63.6,52
39,HDFCBANK,https://mkt.in/static/mkt-icons/nifty100/HDFCB...,HDFC Bank Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,HDFC Bank Limited (also known as HDFC) is an I...,http://www.hdfcbank.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/hdf...,1,601,7.67,17.1
67,NESTLEIND,https://mkt.in/static/mkt-icons/nifty100/NESTL...,Nestle India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Nestle India Limited is the Indian subsidiary ...,https://www.nestle.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/nes...,1,41,185.43,135.61
10,ATGL,https://mkt.in/static/mkt-icons/nifty100/ATGL.png,Adani Total Gas Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,AGL is engaged in City Gas Distribution (CGD) ...,http://www.adanigas.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,36,21.2,20.5
44,ICICIBANK,https://mkt.in/static/mkt-icons/nifty100/ICICI...,ICICI Bank Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,ICICI Bank is the second-largest private secto...,http://www.icicibank.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ici...,2,365,7.6,18.8

## 12. Complete Data Profile

We consolidate all the column metadata we just explored (data types, missing values, unique counts) into a single profile DataFrame for a unified view.

In [26]:
profile = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Missing": df.isnull().sum(),
    "Missing %": round(df.isnull().mean()*100,2),
    "Unique": df.nunique()
})
profile

                                                                                               Column Data Type  Missing  Missing %  Unique
Mkt Fintech — Nifty 100  |  Companies  |  92 re...  Mkt Fintech — Nifty 100  |  Companies  |  92 r...       str        0       0.00      93
Unnamed: 1                                                                                 Unnamed: 1       str        1       1.08      91
Unnamed: 2                                                                                 Unnamed: 2       str        0       0.00      93
Unnamed: 3                                                                                 Unnamed: 3       str        0       0.00      55
Unnamed: 4                                                                                 Unnamed: 4       str        0       0.00      93
Unnamed: 5                                                                                 Unnamed: 5       str        1       1.08      91
Unnamed: 6                                                                                 Unnamed: 6       str        1       1.08      92
Unnamed: 7                                                                                 Unnamed: 7       str        1       1.08      92
Unnamed: 8                                                                                 Unnamed: 8    object        1       1.08       5
Unnamed: 9                                                                                 Unnamed: 9    object        1       1.08      85
Unnamed: 10                                                                               Unnamed: 10    object        1       1.08      85
Unnamed: 11                                                                               Unnamed: 11    object        2       2.15      86

## 13. Export Profile

We save our consolidated data profile as a CSV report so we can review it later or share it with stakeholders.

In [27]:
REPORT_PATH = PROJECT_ROOT / "reports"
REPORT_PATH.mkdir(exist_ok=True)

profile.to_csv(
    REPORT_PATH / "companies_profile.csv",
    index=False
)

print("Profile Exported Successfully")

Profile Exported Successfully

## 14. Data Quality Checks

We summarize the overall health of the dataset by restating the total rows, total duplicates, and a breakdown of all missing values.

In [28]:
print("=" * 60)
print("DATA QUALITY CHECK")
print("=" * 60)

print("Total Rows :", len(df))
print("Duplicate Rows :", df.duplicated().sum())
print("Total Missing :", df.isnull().sum().sum())

display(df.isnull().sum())

============================================================
DATA QUALITY CHECK
============================================================
Total Rows : 93
Duplicate Rows : 0
Total Missing : 9

Mkt Fintech — Nifty 100  |  Companies  |  92 records    0
Unnamed: 1                                              1
Unnamed: 2                                              0
Unnamed: 3                                              0
Unnamed: 4                                              0
Unnamed: 5                                              1
Unnamed: 6                                              1
Unnamed: 7                                              1
Unnamed: 8                                              1
Unnamed: 9                                              1
Unnamed: 10                                             1
Unnamed: 11                                             2
dtype: int64

## 15. Save Clean Copy

Finally, we export the DataFrame as a `.csv` file to our processed data folder so it is ready for the next stages of financial analysis.

In [29]:
PROCESSED = PROJECT_ROOT / "data" / "processed"
PROCESSED.mkdir(exist_ok=True)

df.to_csv(
    PROCESSED / "companies.csv",
    index=False
)

print("Clean CSV Saved Successfully")

Clean CSV Saved Successfully