## 1. Import Libraries

We install our dependencies and import libraries required for our data quality engine.

In [2]:
# Install required libraries
%pip install pandas numpy openpyxl matplotlib jinja2

import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

Requirement already satisfied: pandas in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (2.4.4)
Requirement already satisfied: openpyxl in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.11.0)
Requirement already satisfied: jinja2 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\polai\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\polai\appdata\roaming\python\python313\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=9 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\polai\appdata\local\programs\python\python313\lib\site-packages (from jinja2) (3.0.3)
Requirement already satisfied: six>=1.5 in c:\users\polai\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## 2. Project Paths

We dynamically determine the project root folder regardless of where the notebook was launched, and establish paths to our raw data and reports.

In [3]:
current_dir = Path.cwd()

# Dynamically resolve the project root
if current_dir.name == "notebooks":
    PROJECT_ROOT = current_dir.parent
else:
    PROJECT_ROOT = current_dir

RAW_DATA = PROJECT_ROOT / "data" / "raw"
REPORT_PATH = PROJECT_ROOT / "reports"

# Ensure the reports directory exists
REPORT_PATH.mkdir(exist_ok=True)

print("Project Root:", PROJECT_ROOT)
print("Raw Data:", RAW_DATA)

Project Root: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform
Raw Data: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform\data\raw

## 3. Find All Excel Files

We locate and list all the Excel datasets in our raw data directory that will be scanned for quality.

In [4]:
excel_files = sorted(RAW_DATA.glob("*.xlsx"))

print(f"Datasets Found: {len(excel_files)}")

for file in excel_files:
    print(file.name)

Datasets Found: 7
analysis.xlsx
balancesheet.xlsx
cashflow.xlsx
companies.xlsx
documents.xlsx
profitandloss.xlsx
prosandcons.xlsx

## 4. Data Quality Analysis

We scan every dataset, calculating total rows, columns, missing values, duplicates, and memory usage to compile a comprehensive data quality report.

In [5]:
quality_report = []

for file in excel_files:
    try:
        df = pd.read_excel(file)

        quality_report.append({
            "Dataset": file.name,
            "Rows": len(df),
            "Columns": len(df.columns),
            "Missing Values": int(df.isnull().sum().sum()),
            "Duplicate Rows": int(df.duplicated().sum()),
            "Memory Usage (KB)": round(df.memory_usage(deep=True).sum()/1024, 2)
        })
    except Exception as e:
        print(f"Error reading {file.name}: {e}")

quality_df = pd.DataFrame(quality_report)
quality_df

Error reading balancesheet.xlsx: [Errno 13] Permission denied: 'c:\\Users\\polai\\OneDrive\\Desktop\\N100 FINANCIAL INTELLIGENCE PLATFORM\\nifty100-financial-intelligence-platform\\data\\raw\\balancesheet.xlsx'

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Memory Usage (KB)
0,analysis.xlsx,21,6,0,0,8.00
1,cashflow.xlsx,1188,7,8,0,340.11
2,companies.xlsx,93,12,9,0,100.14
3,documents.xlsx,1586,4,52,0,361.04
4,profitandloss.xlsx,1277,15,231,0,723.63
5,prosandcons.xlsx,17,4,6,0,4.51

## 5. Missing Values by Dataset

We break down the missing values for each column across all datasets.

In [ ]:
for file in excel_files:
    try:
        print("=" * 70)
        print(file.name)
        df = pd.read_excel(file)
        display = None
        display(df.isnull().sum())
    except:
        pass

======================================================================
analysis.xlsx

Bluestock Fintech — Nifty 100  |  Analysis  |  20 records    0
Unnamed: 1                                                   0
Unnamed: 2                                                   0
Unnamed: 3                                                   0
Unnamed: 4                                                   0
Unnamed: 5                                                   0
dtype: int64

======================================================================
balancesheet.xlsx
======================================================================
cashflow.xlsx

Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records    0
Unnamed: 1                                                       0
Unnamed: 2                                                       0
Unnamed: 3                                                       2
Unnamed: 4                                                       2
Unnamed: 5                                                       2
Unnamed: 6                                                       2
dtype: int64

======================================================================
companies.xlsx

Mkt Fintech — Nifty 100  |  Companies  |  92 records    0
Unnamed: 1                                              1
Unnamed: 2                                              0
Unnamed: 3                                              0
Unnamed: 4                                              0
Unnamed: 5                                              1
Unnamed: 6                                              1
Unnamed: 7                                              1
Unnamed: 8                                              1
Unnamed: 9                                              1
Unnamed: 10                                             1
Unnamed: 11                                             2
dtype: int64

======================================================================
documents.xlsx

Bluestock Fintech — Nifty 100  |  Documents  |  1,585 records     0
Unnamed: 1                                                        0
Unnamed: 2                                                        0
Unnamed: 3                                                       52
dtype: int64

======================================================================
profitandloss.xlsx

Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records      0
Unnamed: 1                                                             0
Unnamed: 2                                                             0
Unnamed: 3                                                             0
Unnamed: 4                                                             0
Unnamed: 5                                                            13
Unnamed: 6                                                            15
Unnamed: 7                                                             0
Unnamed: 8                                                             0
Unnamed: 9                                                             0
Unnamed: 10                                                            0
Unnamed: 11                                                           95
Unnamed: 12                                                            0
Unnamed: 13                                                            5
Unnamed: 14                                                          103
dtype: int64

======================================================================
prosandcons.xlsx

Bluestock Fintech — Nifty 100  |  Pros & Cons  |  16 records    0
Unnamed: 1                                                      0
Unnamed: 2                                                      5
Unnamed: 3                                                      1
dtype: int64

## 6. Duplicate Rows

We extract exactly how many rows are completely duplicated in each file.

In [7]:
duplicates = []

for file in excel_files:
    try:
        df = pd.read_excel(file)
        duplicates.append({
            "Dataset": file.name,
            "Duplicate Rows": int(df.duplicated().sum())
        })
    except:
        pass

duplicates_df = pd.DataFrame(duplicates)
duplicates_df

              Dataset  Duplicate Rows
0       analysis.xlsx               0
1       cashflow.xlsx               0
2      companies.xlsx               0
3      documents.xlsx               0
4  profitandloss.xlsx               0
5    prosandcons.xlsx               0

## 7. Data Types

We inspect the Pandas-inferred data types for all columns across every dataset to ensure consistency.

In [8]:
for file in excel_files:
    try:
        print("=" * 60)
        print(file.name)
        df = pd.read_excel(file)
        display(df.dtypes)
    except:
        pass

============================================================
analysis.xlsx

Bluestock Fintech — Nifty 100  |  Analysis  |  20 records    str
Unnamed: 1                                                   str
Unnamed: 2                                                   str
Unnamed: 3                                                   str
Unnamed: 4                                                   str
Unnamed: 5                                                   str
dtype: object

============================================================
balancesheet.xlsx
============================================================
cashflow.xlsx

Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records    object
Unnamed: 1                                                          str
Unnamed: 2                                                          str
Unnamed: 3                                                       object
Unnamed: 4                                                       object
Unnamed: 5                                                       object
Unnamed: 6                                                       object
dtype: object

============================================================
companies.xlsx

Mkt Fintech — Nifty 100  |  Companies  |  92 records       str
Unnamed: 1                                                 str
Unnamed: 2                                                 str
Unnamed: 3                                                 str
Unnamed: 4                                                 str
Unnamed: 5                                                 str
Unnamed: 6                                                 str
Unnamed: 7                                                 str
Unnamed: 8                                              object
Unnamed: 9                                              object
Unnamed: 10                                             object
Unnamed: 11                                             object
dtype: object

============================================================
documents.xlsx

Bluestock Fintech — Nifty 100  |  Documents  |  1,585 records    object
Unnamed: 1                                                          str
Unnamed: 2                                                       object
Unnamed: 3                                                          str
dtype: object

============================================================
profitandloss.xlsx

Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records    object
Unnamed: 1                                                              str
Unnamed: 2                                                              str
Unnamed: 3                                                           object
Unnamed: 4                                                           object
Unnamed: 5                                                           object
Unnamed: 6                                                           object
Unnamed: 7                                                           object
Unnamed: 8                                                           object
Unnamed: 9                                                           object
Unnamed: 10                                                          object
Unnamed: 11                                                          object
Unnamed: 12                                                          object
Unnamed: 13                                                          object
Unnamed: 14                                                          object
dtype: object

============================================================
prosandcons.xlsx

Bluestock Fintech — Nifty 100  |  Pros & Cons  |  16 records    object
Unnamed: 1                                                         str
Unnamed: 2                                                         str
Unnamed: 3                                                         str
dtype: object

## 8. Dataset Health Score

We calculate a custom 'Health Score' starting at 100, deducting points for missing values and duplicates to give each dataset a quality grade.

In [9]:
if not quality_df.empty:
    quality_df["Health Score"] = 100
    quality_df["Health Score"] -= quality_df["Missing Values"] * 0.05
    quality_df["Health Score"] -= quality_df["Duplicate Rows"] * 2
    quality_df["Health Score"] = quality_df["Health Score"].clip(lower=0)

quality_df

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Memory Usage (KB),Health Score
0,analysis.xlsx,21,6,0,0,8.00,100.00
1,cashflow.xlsx,1188,7,8,0,340.11,99.60
2,companies.xlsx,93,12,9,0,100.14,99.55
3,documents.xlsx,1586,4,52,0,361.04,97.40
4,profitandloss.xlsx,1277,15,231,0,723.63,88.45
5,prosandcons.xlsx,17,4,6,0,4.51,99.70

## 9. Save Report

We export the finalized Data Quality Report as a CSV file to our reports folder for project documentation.

In [10]:
if not quality_df.empty:
    quality_df.to_csv(
        REPORT_PATH / "data_quality_report.csv",
        index=False
    )
    print("Data Quality Report Saved Successfully")
else:
    print("No data to save.")

Data Quality Report Saved Successfully

## 10. Summary

We aggregate the metrics into a final grand total to understand the overall health and scope of our data ecosystem.

In [11]:
print("=" * 60)
print("DATA QUALITY SUMMARY")
print("=" * 60)

if not quality_df.empty:
    print("Datasets:", len(quality_df))
    print("Total Rows:", quality_df["Rows"].sum())
    print("Total Missing:", quality_df["Missing Values"].sum())
    print("Total Duplicates:", quality_df["Duplicate Rows"].sum())
    display(quality_df)
else:
    print("No data available to summarize.")

============================================================
DATA QUALITY SUMMARY
============================================================
Datasets: 6
Total Rows: 4182
Total Missing: 306
Total Duplicates: 0

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Memory Usage (KB),Health Score
0,analysis.xlsx,21,6,0,0,8.00,100.00
1,cashflow.xlsx,1188,7,8,0,340.11,99.60
2,companies.xlsx,93,12,9,0,100.14,99.55
3,documents.xlsx,1586,4,52,0,361.04,97.40
4,profitandloss.xlsx,1277,15,231,0,723.63,88.45
5,prosandcons.xlsx,17,4,6,0,4.51,99.70