## 1. Import Libraries

We import `pandas` and `pathlib` for file routing and structured data analysis.

In [1]:
import pandas as pd
from pathlib import Path
import sys

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

## 2. Set Project Paths

Establish the absolute paths to locate our raw datasets and supporting spreadsheets, dynamically resolving relative to the Jupyter execution folder.

In [2]:
current_dir = Path.cwd()
PROJECT_ROOT = current_dir.parent if current_dir.name == "notebooks" else current_dir

RAW_DATA = PROJECT_ROOT / "data" / "raw"
SUPPORTING_DATA = PROJECT_ROOT / "data" / "supporting"

print(f"Project Root: {PROJECT_ROOT}")
print(f"Raw Data Path: {RAW_DATA}")
print(f"Supporting Data Path: {SUPPORTING_DATA}")

Project Root: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform
Raw Data Path: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform\data\raw
Supporting Data Path: c:\Users\polai\OneDrive\Desktop\N100 FINANCIAL INTELLIGENCE PLATFORM\nifty100-financial-intelligence-platform\data\supporting

## 3. Discover All Excel Files

Scan both folders for Excel spreadsheets and compile a master list of files to analyze.

In [3]:
raw_files = sorted(RAW_DATA.glob("*.xlsx"))
supporting_files = sorted(SUPPORTING_DATA.glob("*.xlsx"))

excel_files = raw_files + supporting_files

print(f"Total Datasets: {len(excel_files)}")

for file in excel_files:
    print(file.name)

Total Datasets: 12
analysis.xlsx
balancesheet.xlsx
cashflow.xlsx
companies.xlsx
documents.xlsx
profitandloss.xlsx
prosandcons.xlsx
financial_ratios.xlsx
market_cap.xlsx
peer_groups.xlsx
sectors.xlsx
stock_prices.xlsx

## 4. Analyze Every Dataset

Read each Excel file to retrieve structural metadata: row counts, column counts, and column header names.

In [4]:
summary = []

for file in excel_files:
    try:
        df = pd.read_excel(file)
        summary.append({
            "Dataset": file.name,
            "Rows": len(df),
            "Columns": len(df.columns),
            "Column Names": ", ".join(map(str, df.columns))
        })
    except Exception as e:
        print(f"Failed to read {file.name}: {e}")

summary_df = pd.DataFrame(summary)
display(summary_df)

                  Dataset  Rows  Columns                                       Column Names
0           analysis.xlsx    21        6  Bluestock Fintech — Nifty 100  |  Analysis  | ...
1       balancesheet.xlsx  1313       13  Bluestock Fintech — Nifty 100  |  Balance Shee...
2           cashflow.xlsx  1188        7  Bluestock Fintech — Nifty 100  |  Cash Flow  |...
3          companies.xlsx    93       12  Mkt Fintech — Nifty 100  |  Companies  |  92 r...
4          documents.xlsx  1586        4  Bluestock Fintech — Nifty 100  |  Documents  |...
5      profitandloss.xlsx  1277       15  Bluestock Fintech — Nifty 100  |  Profit & Los...
6        prosandcons.xlsx    17        4  Bluestock Fintech — Nifty 100  |  Pros & Cons ...
7   financial_ratios.xlsx  1184       16  id, company_id, year, net_profit_margin_pct, o...
8         market_cap.xlsx   552        9  id, company_id, year, market_cap_crore, enterp...
9        peer_groups.xlsx    56        4      id, peer_group_name, company_id, is_benchmark
10           sectors.xlsx    92        6  id, company_id, broad_sector, sub_sector, inde...
11      stock_prices.xlsx  5520        9  id, company_id, date, open_price, high_price, ...

## 5. Save Mapping Report

Export the structural analysis to `/reports/dataset_mapping_report.csv` for structural mapping tasks.

In [5]:
REPORT_PATH = PROJECT_ROOT / "reports"
REPORT_PATH.mkdir(exist_ok=True)

summary_df.to_csv(
    REPORT_PATH / "dataset_mapping_report.csv",
    index=False

)

print("Dataset Mapping Report Generated Successfully!")

Dataset Mapping Report Generated Successfully!

## 6. Inspect Master Dataset in Detail

Analyze the master `companies.xlsx` file. We print its head, raw data types, and check for missing fields.

In [6]:
df_comp = pd.read_excel(RAW_DATA / "companies.xlsx")

display(df_comp.head())

print("\n--- Data Types ---")
print(df_comp.dtypes)

print("\n--- Missing Values ---")
print(df_comp.isnull().sum())

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

--- Data Types ---
Mkt Fintech — Nifty 100  |  Companies  |  92 records       str
Unnamed: 1                                                 str
Unnamed: 2                                                 str
Unnamed: 3                                                 str
Unnamed: 4                                                 str
Unnamed: 5                                                 str
Unnamed: 6                                                 str
Unnamed: 7                                                 str
Unnamed: 8                                              object
Unnamed: 9                                              object
Unnamed: 10                                             object
Unnamed: 11                                             object
dtype: object

--- Missing Values ---
Mkt Fintech — Nifty 100  |  Companies  |  92 records    0
Unnamed: 1                                              1
Unnamed: 2                                              0
Unnamed: 3                                              0
Unnamed: 4                                              0
Unnamed: 5                                              1
Unnamed: 6                                              1
Unnamed: 7                                              1
Unnamed: 8                                              1
Unnamed: 9                                              1
Unnamed: 10                                             1
Unnamed: 11                                             2
dtype: int64

## 7. Inspect Financial Datasets in Detail

Print detailed summaries (head, dtypes, nulls) for `profitandloss.xlsx`, `balancesheet.xlsx`, and `cashflow.xlsx`.

In [7]:
financials = ["profitandloss.xlsx", "balancesheet.xlsx", "cashflow.xlsx"]

for fn in financials:
    print("=" * 80)
    print(f"FINANCIAL FILE: {fn}")
    print("=" * 80)
    
    try:
        df_f = pd.read_excel(RAW_DATA / fn)
        display(df_f.head(3))
        print("\nData Types:")
        print(df_f.dtypes)
        print("\nMissing Values:")
        print(df_f.isnull().sum())
        print("\n")
    except Exception as e:
        print(f"Could not load {fn}: {e}\n")

================================================================================
FINANCIAL FILE: profitandloss.xlsx
================================================================================

,"Bluestock Fintech — Nifty 100 | Profit & Loss | 1,276 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25

Data Types:
Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records    object
Unnamed: 1                                                              str
Unnamed: 2                                                              str
Unnamed: 3                                                           object
Unnamed: 4                                                           object
Unnamed: 5                                                           object
Unnamed: 6                                                           object
Unnamed: 7                                                           object
Unnamed: 8                                                           object
Unnamed: 9                                                           object
Unnamed: 10                                                          object
Unnamed: 11                                                          object
Unnamed: 12                                                          object
Unnamed: 13                                                          object
Unnamed: 14                                                          object
dtype: object

Missing Values:
Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records      0
Unnamed: 1                                                             0
Unnamed: 2                                                             0
Unnamed: 3                                                             0
Unnamed: 4                                                             0
Unnamed: 5                                                            13
Unnamed: 6                                                            15
Unnamed: 7                                                             0
Unnamed: 8                                                             0
Unnamed: 9                                                             0
Unnamed: 10                                                            0
Unnamed: 11                                                           95
Unnamed: 12                                                            0
Unnamed: 13                                                            5
Unnamed: 14                                                          103
dtype: int64


================================================================================
FINANCIAL FILE: balancesheet.xlsx
================================================================================

,"Bluestock Fintech — Nifty 100 | Balance Sheet | 1,312 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
1,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
2,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139

Data Types:
Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records    object
Unnamed: 1                                                              str
Unnamed: 2                                                              str
Unnamed: 3                                                           object
Unnamed: 4                                                           object
Unnamed: 5                                                           object
Unnamed: 6                                                           object
Unnamed: 7                                                           object
Unnamed: 8                                                           object
Unnamed: 9                                                           object
Unnamed: 10                                                          object
Unnamed: 11                                                          object
Unnamed: 12                                                          object
dtype: object

Missing Values:
Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records    0
Unnamed: 1                                                           0
Unnamed: 2                                                           0
Unnamed: 3                                                           0
Unnamed: 4                                                           0
Unnamed: 5                                                           0
Unnamed: 6                                                           0
Unnamed: 7                                                           0
Unnamed: 8                                                           0
Unnamed: 9                                                           0
Unnamed: 10                                                          0
Unnamed: 11                                                          0
Unnamed: 12                                                          0
dtype: int64


================================================================================
FINANCIAL FILE: cashflow.xlsx
================================================================================

  Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records  Unnamed: 1 Unnamed: 2          Unnamed: 3          Unnamed: 4          Unnamed: 5     Unnamed: 6
0                                                 id             company_id       year  operating_activity  investing_activity  financing_activity  net_cash_flow
1                                                 37                    TCS     Mar-13               11615               -6038               -5729           -152
2                                                 38                    TCS     Mar-14               14751               -9452               -5673           -374

Data Types:
Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records    object
Unnamed: 1                                                          str
Unnamed: 2                                                          str
Unnamed: 3                                                       object
Unnamed: 4                                                       object
Unnamed: 5                                                       object
Unnamed: 6                                                       object
dtype: object

Missing Values:
Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records    0
Unnamed: 1                                                       0
Unnamed: 2                                                       0
Unnamed: 3                                                       2
Unnamed: 4                                                       2
Unnamed: 5                                                       2
Unnamed: 6                                                       2
dtype: int64